#!/bin/sh
set -eu
cd "$(dirname "$0")"
python3 tools/native_media_tables.py "${KISAKU_EXE:-鬼作/AI6WIN.exe}" build/media_tables.h
python3 tools/native_bowling_tables.py "${KISAKU_EXE:-鬼作/AI6WIN.exe}" build/bowling_tables.h
mkdir -p build
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tools/bootstrap_probe.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/kisaku-bootstrap
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror runtime/lzss.c runtime/ai6arc.c runtime/probe.c -o build/kisaku-probe
  ${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime $(pkg-config --cflags sdl2) \
    runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c runtime/image_sdl.c tools/runtime_viewer.c \
    -lSDL2_test $(pkg-config --libs sdl2) $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/kisaku-runtime

${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/kisaku_bootstrap_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/kisaku-bootstrap-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/save_runtime_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/save-runtime-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/letter_save_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/letter-save-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/transition_cadence_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/transition-cadence-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/vm_capacity_gate_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/vm-capacity-gate-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c tests/scene_completion_stage_test.c $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/scene-completion-stage-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c tools/akb_probe.c -o build/kisaku-akb-probe
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime $(pkg-config --cflags sdl2) \
    runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/vm.c runtime/mov.c runtime/ax.c runtime/mam.c runtime/video.c runtime/flags.c runtime/gallery.c runtime/control_store.c runtime/save_slot.c runtime/scene.c runtime/scene_view.c runtime/title.c runtime/flag_dialog.c runtime/scene_history.c runtime/text_encoding.c runtime/text_layout.c runtime/font.c runtime/read_flags.c runtime/voice_worker.c runtime/image_worker.c runtime/bootstrap.c runtime/switch_hos.c runtime/image_sdl.c tests/message_panel_test.c \
    -lSDL2_test $(pkg-config --libs sdl2) $(pkg-config --cflags --libs libavformat libavcodec libswscale libswresample freetype2) -o build/message-panel-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/rmt.c runtime/akb.c tests/akb_test.c -o build/akb-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/ax.c tests/bowling_asset_test.c -o build/bowling-asset-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/lzss.c runtime/ai6arc.c runtime/rmt.c runtime/akb.c runtime/image_sdl.c tools/image_viewer.c $(pkg-config --cflags --libs sdl2) -lSDL2_test -o build/kisaku-image-viewer

${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/vm.c tests/vm_memory_test.c -o build/vm-memory-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/flags.c tests/flags_test.c -o build/flags-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_test.c -o build/bowling-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime runtime/ax.c tests/param_change_test.c -o build/param-change-test

${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_score_test.c -o build/bowling-score-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_player_test.c -o build/bowling-player-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_throw_test.c -lm -o build/bowling-throw-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_motion_test.c -lm -o build/bowling-motion-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_match_test.c -o build/bowling-match-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_contact_test.c -lm -o build/bowling-contact-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_world_test.c -lm -o build/bowling-world-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_cpu_throw_test.c -lm -o build/bowling-cpu-throw-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_session_test.c -lm -o build/bowling-session-test

${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_projection_test.c -lm -o build/bowling-projection-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_rack_test.c -lm -o build/bowling-rack-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_draw_test.c runtime/ai6arc.c runtime/lzss.c runtime/akb.c runtime/rmt.c -lm -o build/bowling-draw-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_turn_test.c -lm -o build/bowling-turn-test
${CC:-cc} -std=c11 -O2 -Wall -Wextra -Werror -Iruntime tests/bowling_game_test.c -lm -o build/bowling-game-test
