#ifndef KISAKU_SCENE_MODE_CATALOG_H
#define KISAKU_SCENE_MODE_CATALOG_H
#include <stdint.h>
/* Generated by extract_scene_mode_catalog.py; Japanese EXE bb12a3faa7f2147b772a4e8d2235e815c3207e16c57b82882280bc08ce61f3a9. */
static const uint8_t kscene_mode_counts[11]={19,23,18,23,22,18,17,18,15,11,22};
static const uint8_t kscene_mode_resource_group[11]={4,0,3,1,6,7,2,5,8,9,10};
static inline unsigned kscene_mode_total(void){unsigned n=0;for(unsigned i=0;i<11;i++)n+=kscene_mode_counts[i];return n;}
static inline int kscene_mode_at(unsigned flat,unsigned *cat,unsigned *item){unsigned base=0;for(unsigned c=0;c<11;c++){if(flat<base+kscene_mode_counts[c]){if(cat)*cat=c;if(item)*item=flat-base;return 0;}base+=kscene_mode_counts[c];}return -1;}
#endif
