#!/usr/bin/env python3
"""Extract CScMode's read-only category tables from the Japanese AI6WIN EXE.
No executable code is run; the output is a tiny runtime header containing only
counts, resource-group IDs and completion-byte indices for the scene selector."""
import argparse,hashlib,struct
from pathlib import Path
SHA='bb12a3faa7f2147b772a4e8d2235e815c3207e16c57b82882280bc08ce61f3a9'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('exe');ap.add_argument('out');a=ap.parse_args();d=Path(a.exe).read_bytes()
 if hashlib.sha256(d).hexdigest()!=SHA: raise SystemExit('unsupported Japanese executable SHA256')
 pe=struct.unpack_from('<I',d,0x3c)[0];n=struct.unpack_from('<H',d,pe+6)[0];sz=struct.unpack_from('<H',d,pe+20)[0];opt=pe+24;base=struct.unpack_from('<I',d,opt+28)[0];sec=[]
 for i in range(n):
  o=opt+sz+i*40;vs,rva,size,raw=struct.unpack_from('<IIII',d,o+8);sec.append((base+rva,size,raw))
 def read(va,n):
  for start,size,raw in sec:
   if start<=va and va+n<=start+size:return d[raw+va-start:raw+va-start+n]
  raise ValueError(hex(va))
 counts=tuple(read(0x523368,11));groups=tuple(read(0x547c74,11))
 if any(x==0 or x>27 for x in counts):raise SystemExit('invalid category count table')
 out='''#ifndef KISAKU_SCENE_MODE_CATALOG_H\n#define KISAKU_SCENE_MODE_CATALOG_H\n#include <stdint.h>\n/* Generated by extract_scene_mode_catalog.py; Japanese EXE %s. */\nstatic const uint8_t kscene_mode_counts[11]={%s};\nstatic const uint8_t kscene_mode_resource_group[11]={%s};\nstatic inline unsigned kscene_mode_total(void){unsigned n=0;for(unsigned i=0;i<11;i++)n+=kscene_mode_counts[i];return n;}\nstatic inline int kscene_mode_at(unsigned flat,unsigned *cat,unsigned *item){unsigned base=0;for(unsigned c=0;c<11;c++){if(flat<base+kscene_mode_counts[c]){if(cat)*cat=c;if(item)*item=flat-base;return 0;}base+=kscene_mode_counts[c];}return -1;}\n#endif\n'''%(SHA,','.join(map(str,counts)),','.join(map(str,groups)))
 flags=struct.unpack('<297H',read(0x523378,594))
 hage=struct.unpack('<60I',read(0x5a3748,240))[::2]
 if any(x>=9192 for x in flags+hage):raise SystemExit('invalid scene flag table')
 tables='static const uint16_t kscene_mode_flags[11][27]={\n'+''.join(' {'+','.join(map(str,flags[c*27:c*27+27]))+'},\n' for c in range(11))+'};\n'
 tables+='static const uint16_t kscene_mode_hage_flags[30]={'+','.join(map(str,hage))+'};\n'
 out=out.replace('#endif',tables+'#endif')
 Path(a.out).write_text(out)
if __name__=='__main__':main()
