"""Generate portable Unicode mappings from Python's standard codec tables.

No game resources are read. Run from the project root with Python 3.
The double-byte layout is lead 81..FE, trail 40..FE except 7F.
"""
from pathlib import Path


def codepoint(data, encoding):
    try:
        text = data.decode(encoding)
    except UnicodeDecodeError:
        return 0
    return ord(text) if len(text) == 1 else 0


def generate():
    lines = ["/* Generated by tools/generate_codepages.py; standard CP932/GBK mappings. */"]
    for encoding in ("cp932", "gbk"):
        tables = {
            "single": [codepoint(bytes([b]), encoding) for b in range(256)],
            "double": [codepoint(bytes([a, b]), encoding)
                       for a in range(0x81, 0xff)
                       for b in range(0x40, 0xff) if b != 0x7f],
        }
        for name, values in tables.items():
            lines.append(f"static const uint16_t {encoding}_{name}[{len(values)}]={{")
            lines.extend("    " + ",".join(f"0x{v:04x}" for v in values[i:i + 16]) + ","
                         for i in range(0, len(values), 16))
            lines.append("};")
    Path("runtime/codepages.inc").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    generate()
