"""Extract the native alternate-thumbnail decisions (4176f0..417bcf).

Interpret only integer moves/tests/branches, with real bmptbl unlock IDs.
The resulting small truth tables contain no game artwork.
"""
from pathlib import Path
import itertools, random, struct
import capstone
from native_scene_routes import ins,P,BASE
from ai6arc import Archive

DATA=Archive('游戏日文数据/game/ELFIMAGE/data.arc')
BMP=DATA.read('bmptbl.dat')
CAT=DATA.read('cglist.dat')
ALIASES={'al':('eax',0,8),'cl':('ecx',0,8),'dl':('edx',0,8),
         'ax':('eax',0,16),'cx':('ecx',0,16),'dx':('edx',0,16)}
def native(group,page,item,flags):
    regs={'eax':page,'ecx':group,'edx':item,'esp':0x100000}
    memory={0x10000c:0xffffffff};reads=[];zero=False;at=0x4176f0
    def reg(name):
        full,shift,bits=ALIASES.get(name,(name,0,32))
        return regs.get(full,0)>>shift&((1<<bits)-1)
    def get(a,o):
        if o.type==capstone.x86.X86_OP_IMM:return o.imm&0xffffffff
        if o.type==capstone.x86.X86_OP_REG:return reg(a.reg_name(o.reg))
        addr=reg(a.reg_name(o.mem.base))+reg(a.reg_name(o.mem.index))*o.mem.scale+o.mem.disp
        if 0x4ffa68<=addr<0x4ffa68+len(BMP):return int.from_bytes(BMP[addr-0x4ffa68:addr-0x4ffa68+o.size],'little')
        if 0x4ff528<=addr<0x4ff528+1337:
            key=addr-0x4ff528
            if key not in reads:reads.append(key)
            return flags.get(key,0)
        return memory[addr]
    for _ in range(200):
        if at==0x417bcf:return memory[0x10000c],reads
        a=ins(at);o=a.operands;nextat=at+a.size;op=a.mnemonic
        if op in ('mov','movzx'):
            value=get(a,o[1])
            if o[0].type==capstone.x86.X86_OP_REG:
                name=a.reg_name(o[0].reg);full,shift,bits=ALIASES.get(name,(name,0,32));mask=((1<<bits)-1)<<shift
                regs[full]=(regs.get(full,0)&~mask)|((value<<shift)&mask)
            else:
                assert o[0].mem.base==capstone.x86.X86_REG_ESP
                memory[regs['esp']+o[0].mem.disp]=value
        elif op in ('cmp','test'):
            x,y=get(a,o[0]),get(a,o[1]);zero=(x==y) if op=='cmp' else not(x&y)
        elif op=='jmp' or (op=='je' and zero) or (op=='jne' and not zero):nextat=get(a,o[0])
        elif op not in ('je','jne'):raise ValueError((hex(at),op))
        at=nextat
    raise RuntimeError('native branch budget')

def generate():
    rows=[];rng=random.Random(913)
    for group in range(7):
        off=struct.unpack_from('<I',CAT,group*4)[0]
        for raw in range(CAT[off+1]):
            result,ids=native(group,raw//14,raw%14,{})
            assert result==0xffffffff
            if not ids:continue
            assert len(ids)<=4
            values=[]
            for mask in range(1<<len(ids)):
                value,_=native(group,raw//14,raw%14,{key:(mask>>i)&1 for i,key in enumerate(ids)})
                values.append(-1 if value==0xffffffff else value)
            for _ in range(100):
                flags={key:rng.choice([0,0,1,7,255]) for key in range(1336)}
                value,_=native(group,raw//14,raw%14,flags)
                mask=sum((flags[key]!=0)<<i for i,key in enumerate(ids))
                assert values[mask]==(-1 if value==0xffffffff else value)
            rows.append((group,raw,ids,values))
    out=['/* Native 4176f0..417bcf. Generated by tools/generate_gallery_thumbnails.py. */']
    for group,raw,ids,values in rows:
        out.append('{%d,%d,%d,{%s},{%s}},'%(group,raw,len(ids),','.join(map(str,ids)),','.join(map(str,values))))
    Path('runtime/gallery_thumbnails.inc').write_text('\n'.join(out)+'\n')
    print(f'{len(rows)} alternate thumbnail rules; all truth tables and {100*len(rows)} random flag distributions verified')
    # Independent full-page oracle: geometry comes from the executable's
    # jump/position tables, not the portable renderer's copied constants.
    states=[bytes(1337),bytes([1])*1337]+[bytes(rng.choice([0,0,1,7,255]) for _ in range(1337)) for _ in range(12)]
    output=bytearray(b'KGT1'+struct.pack('<I',len(states)))
    for state in states:
        output+=state;records=[]
        for group in range(7):
            off=struct.unpack_from('<I',CAT,group*4)[0];raws=[]
            for raw in range(CAT[off+1]):
                e=struct.unpack_from('<I',CAT,off+2+raw*4)[0]
                if CAT[e+2]:raws.append((raw,e))
            for item,(raw,e) in enumerate(raws):
                page,index=divmod(raw,14);count=sum(r//14==page for r,_ in raws)
                unlock=struct.unpack_from('<H',CAT,e)[0]
                tile=index if state[unlock] else native(group,page,index,dict(enumerate(state)))[0]
                records.append((group,item,page,CAT[off]+(group==5),index,count,item-index,tile))
            if group==5:
                for i in range(14):records.append((group,len(raws)+i,4,5,i,14,len(raws),i if state[i] else 0xffffffff))
        output+=struct.pack('<I',len(records))
        for group,item,page,pages,index,count,first,tile in records:
            handler=struct.unpack('<I',P.get_data(0x4182b4-BASE+(count-5)*4,4))[0]
            positions=ins(handler).operands[1].imm
            position=P.get_data(positions-BASE+index,1)[0]
            output+=struct.pack('<10I',group,item,page,pages,index,count,first,tile,40+position%4*128,48+position//4*98)
    Path('local/gallery-thumbnail-reference.bin').write_bytes(output)
    print(f'{len(states)*len(records)} full thumbnail records exported for C comparison')
if __name__=='__main__':generate()
