"""Extract verified media metadata from the Japanese EXE without executing it.
Generated header stays in ignored build/, never embeds graphics or dialogue.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import struct
import tempfile

EXE_SHA256 = 'bb12a3faa7f2147b772a4e8d2235e815c3207e16c57b82882280bc08ce61f3a9'

def extract(path):
    data = Path(path).read_bytes()
    if hashlib.sha256(data).hexdigest() != EXE_SHA256:
        raise ValueError('Unsupported EXE: Japanese executable SHA256 mismatch')
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    count = struct.unpack_from('<H', data, pe + 6)[0]
    optsize = struct.unpack_from('<H', data, pe + 20)[0]
    optional = pe + 24
    base = struct.unpack_from('<I', data, optional + 28)[0]
    sections = []
    for i in range(count):
        off = optional + optsize + i * 40
        _, rva, size, raw = struct.unpack_from('<IIII', data, off + 8)
        sections.append((rva, size, raw))
    def read(va, size):
        rva = va - base
        for start, length, raw in sections:
            if start <= rva and rva + size <= start + length:
                result = data[raw + rva - start:raw + rva - start + size]
                if len(result) == size:
                    return result
        raise ValueError(f'Unmapped static address {va:#x}')
    def name(va):
        chars = bytearray()
        for i in range(1024):
            c = read(va + i, 1)[0]
            if not c:
                value = chars.decode('ascii').upper()
                if not re.fullmatch(r'[A-Z0-9_.-]+', value):
                    raise ValueError('Invalid media resource name')
                return value
            chars.append(c)
        raise ValueError('Unterminated media resource name')
    tables = []
    for va, width, sentinel, expected in [(0x5a8ba0, 10, 0, 1554), (0x5a7080, 10, 0, 72), (0x5b7e98, 3, 1, 189)]:
        records = []
        for i in range(4096):
            row = list(struct.unpack('<' + 'i' * width, read(va + i * width * 4, width * 4)))
            if row[sentinel] == -1:
                break
            row[1 if width == 10 else 0] = name(row[1 if width == 10 else 0])
            records.append(row)
        if len(records) != expected:
            raise ValueError('Static media table count mismatch')
        tables.append(records)
    return tables

def render(tables):
    lines = ['/* Generated by native_media_tables.py; verified EXE ' + EXE_SHA256 + ' */']
    for name, rows in zip(['kisaku_media_main', 'kisaku_media_alternate', 'kisaku_media_links'], tables):
        kind = 'KMediaLink' if name.endswith('links') else 'KMediaRecord'
        lines.append(f'static const {kind} {name}[]={{')
        for row in rows:
            if kind == 'KMediaRecord':
                flag, resource, *conditions = row
                lines.append('{'+f'{flag},{json.dumps(resource)},'+'{'+','.join(map(str, conditions))+'}},')
            else:
                resource, flag, related = row
                lines.append('{'+f'{json.dumps(resource)},{flag},{related}'+'},')
        lines.append('};')
    return '\n'.join(lines) + '\n'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('exe')
    parser.add_argument('output')
    args = parser.parse_args()
    result = render(extract(args.exe))
    output = Path(args.output)
    if output.exists() and output.read_text() == result:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile('w', dir=output.parent, delete=False) as f:
        f.write(result)
        temp = f.name
    os.replace(temp, output)

if __name__ == '__main__':
    main()
